ren src\App.js src\App.tsx
ren src\App.test.js src\App.test.tsx
ren src\index.js src\index.tsx
ren src\reportWebVitals.js src\reportWebVitals.tsx
ren src\setupTests.js src\setupTests.tsx
ren src\components\CoverVideo.js src\components\CoverVideo.tsx
ren src\components\Loader.js src\components\Loader.tsx
ren src\components\LoginButton.js src\components\LoginButton.tsx
ren src\components\LoginModal.js src\components\LoginModal.tsx
ren src\components\Logo.js src\components\Logo.tsx
ren src\components\NavBar.js src\components\NavBar.tsx
ren src\components\ScrollTriggerProxy.js src\components\ScrollTriggerProxy.tsx
ren src\context\AuthContext.js src\context\AuthContext.tsx
ren src\sections\About.js src\sections\About.tsx
ren src\sections\Banner.js src\sections\Banner.tsx
ren src\sections\Footer.js src\sections\Footer.tsx
ren src\sections\Home.js src\sections\Home.tsx
ren src\sections\NewArrival.js src\sections\NewArrival.tsx
ren src\sections\Shop.js src\sections\Shop.tsx
ren src\styles\GlobalStyles.js src\styles\GlobalStyles.tsx
ren src\styles\Themes.js src\styles\Themes.tsx
